/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Abastecimiento;
import javax.swing.ImageIcon;
import java.awt.BorderLayout;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Graphics;
import java.awt.Graphics2D;
import static java.awt.SystemColor.info;
import java.awt.dnd.DropTarget;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author cristian
 */
public class Dotaciones extends javax.swing.JPanel {

    /**
     * Creates new form Dotaciones
     */
     List<TablaDotacion>  tabladotacion;
     Paragraph titulo;
    public Dotaciones() {
       
        tabladotacion = new ArrayList<>();
        initComponents();
        
        //DefaultTableModel model=new DefaultTableModel();
        //Opciones op=new Opciones(model);
     
      
    }
    
   DefaultTableModel model=new DefaultTableModel();
   Opciones op=new Opciones(model);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        BotonGuardar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Text_Cantidad1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TextSelector3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Select_Establecimiento = new javax.swing.JComboBox<>();
        Selec_Dotaciones = new javax.swing.JComboBox<>();
        Limpiar = new javax.swing.JButton();
        Selector3 = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaDotacion = new javax.swing.JTable();
        BTNExport1 = new javax.swing.JButton();
        BTNExport = new javax.swing.JButton();

        setBackground(new java.awt.Color(242, 242, 242));
        setPreferredSize(new java.awt.Dimension(388, 501));

        jScrollPane3.setBackground(new java.awt.Color(242, 242, 242));

        jPanel2.setBackground(new java.awt.Color(242, 242, 242));
        jPanel2.setPreferredSize(new java.awt.Dimension(720, 1000));

        BotonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        BotonGuardar.setText("Guardar");
        BotonGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });

        jLabel3.setText("Adicionales");

        Text_Cantidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_Cantidad1ActionPerformed(evt);
            }
        });
        Text_Cantidad1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Text_Cantidad1KeyTyped(evt);
            }
        });

        jLabel5.setText("Cantidad");

        TextSelector3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextSelector3ActionPerformed(evt);
            }
        });
        TextSelector3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextSelector3KeyTyped(evt);
            }
        });

        jLabel2.setText("Establecimientos");

        jLabel1.setText("Dotaciones");

        Select_Establecimiento.setModel(new javax.swing.DefaultComboBoxModel<>( new String[] {""}));
        Select_Establecimiento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Select_EstablecimientoItemStateChanged(evt);
            }
        });
        Select_Establecimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Select_EstablecimientoMouseClicked(evt);
            }
        });
        Select_Establecimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Select_EstablecimientoActionPerformed(evt);
            }
        });

        Selec_Dotaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "vacio", "Vivienda Unifamiliar", "Edificio Multifamiliar", "Establecimiento de Hospedaje", "Restaurantes","Local de comida al aire", "Local Estudiantil", "Residencia Estudiantil", "Cine", "Teatros", "Auditorios", "Discotecas", "Casinos", "Salas de baile", "Estadios", "Velódromos", "Autódromos", "Plazas de Toros", "Circo", "Hipodromos", "Parque de atracciones", "Piscinas y natatorios", "Oficinas", "Depositos Materiales,equipos y Articulos manufacturados", "Locales comerciales", "Mercados y  Establecimientos", "consumo industrial", "Plantas de produccion e industrialización", "Estaciones de servicio gasolina,garajes y parques de establecimiento", "Edificacions de alojamiento de animales", "Mataderos", "Bares,Cafes", "Locales de Salud", "Lavanderias,Tintorerrias", "Areas Verdes"}));
        Selec_Dotaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Selec_DotacionesMouseClicked(evt);
            }
        });
        Selec_Dotaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Selec_DotacionesActionPerformed(evt);
            }
        });

        Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Actions-edit-delete-icon.png"))); // NOI18N
        Limpiar.setText("Limpiar");
        Limpiar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });

        Selector3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        Selector3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Selector3MouseClicked(evt);
            }
        });
        Selector3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Selector3ActionPerformed(evt);
            }
        });

        TablaDotacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {"Establecimiento","Tipo","Unidades","Dotacion","Consumo","Cantidad","Observaciones"}
        ));
        TablaDotacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TablaDotacionMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TablaDotacionMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(TablaDotacion);

        BTNExport1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/excel.png"))); // NOI18N
        BTNExport1.setText("Excel");
        BTNExport1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BTNExport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNExport1ActionPerformed(evt);
            }
        });

        BTNExport.setBackground(new java.awt.Color(255, 255, 255));
        BTNExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pdf.png"))); // NOI18N
        BTNExport.setText(" PDF");
        BTNExport.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BTNExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Select_Establecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Selec_Dotaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(BotonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TextSelector3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Selector3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(87, 87, 87)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Text_Cantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))))))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(339, Short.MAX_VALUE)
                        .addComponent(Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(239, 239, 239))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(BTNExport, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(BTNExport1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Selec_Dotaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Select_Establecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Selector3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextSelector3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Text_Cantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNExport)
                    .addComponent(BTNExport1))
                .addContainerGap(469, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void Selec_DotacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Selec_DotacionesActionPerformed
        
        
     Select_Establecimiento.removeAllItems();;
     Selector3.removeAllItems(); 
    }//GEN-LAST:event_Selec_DotacionesActionPerformed

    private void TextSelector3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextSelector3ActionPerformed
      
    }//GEN-LAST:event_TextSelector3ActionPerformed

    private void Text_Cantidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_Cantidad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_Cantidad1ActionPerformed

    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed
        //-------Decalracion de variables-------//
        
     CalculosCasos CC=new CalculosCasos();   
     if (TextSelector3.getText().isEmpty() || Text_Cantidad1.getText().isEmpty()){
             getToolkit().beep();
             JOptionPane.showMessageDialog(null,"Por favor, llenar los campos");
     }else{
        float Area,cantidad,consumo;  
        String observacion;
        String textSelector3=TextSelector3.getText();
        //jTextField13.setText(String.valueOf(consumo));
        float Select3=Float.valueOf(textSelector3);
         
          cantidad=Float.valueOf(Text_Cantidad1.getText());
          observacion=jTextField1.getText();
          
        //  Cal_Dotaciones CD=new Cal_Dotaciones();
       
          
         int posicion=Selec_Dotaciones.getSelectedIndex();
         int posicion2=Select_Establecimiento.getSelectedIndex();
         System.out.print(posicion2);
         int pos=Selector3.getSelectedIndex();
         String Establecimiento=Selec_Dotaciones.getItemAt(posicion).toString();
         

         
         textSelector3+=Selector3.getItemAt(pos);
         
         if(posicion2>=0&&pos>=0){
         String tipo=Select_Establecimiento.getItemAt(posicion2).toString();
         CC.CalcularValores(posicion, posicion2, Select3, cantidad);
         
         
         
         TablaDotacion TC = new TablaDotacion();
         TC.setEsta(Establecimiento);
         TC.setTipo(tipo);
         TC.setSelector3(textSelector3);
         TC.setDotacion(String.valueOf(CC.getDotacion()));
         TC.setConsumo(String.valueOf(CC.getConsumo()));
         TC.setCantidad(String.valueOf(CC.getCantidad()));
         TC.setObser(observacion);
         tabladotacion.add(TC);
         
         model=(DefaultTableModel)op.datos_tabla(model,Establecimiento,tipo,textSelector3,CC.getDotacion(),CC.getConsumo(),cantidad,observacion);
         
         
         OpcionesSelector OPS=new OpcionesSelector();
         
         OPS.OpcionesSelector(posicion);
   
         TablaDotacion.setModel(model);
         }else{
         JOptionPane.showMessageDialog(null,"Asegure que todos los selectores esten correctos");
         }    
         
         }
         
         
          
         
         
         
        
         
       
    }//GEN-LAST:event_BotonGuardarActionPerformed

    private void BTNExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNExportActionPerformed
        
        // PRUEBA2 IP=new PRUEBA2();
//ContainPnlpdf pdf=ContainPnlpdf(); 

      try {

      Document documento = new Document();

      String ruta = System.getProperty("user.home");
      PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/OneDrive/Escritorio/" + "CalculosDotacion" + ".pdf"));
      com.itextpdf.text.Image header = com.itextpdf.text.Image.getInstance("src/imagenes/USMP-2020.png");
      header.scaleToFit(200, 400);
      header.setAlignment(Chunk.ALIGN_CENTER);
      Paragraph parrafo = new Paragraph();
      parrafo.setAlignment(Paragraph.ALIGN_CENTER);
      parrafo.add("Tabla 1. Resultado de Calculo de Dotación. \n \n");
      parrafo.setFont(FontFactory.getFont("Tahoma", 18, Font.BOLD, BaseColor.DARK_GRAY));
       titulo= new Paragraph("Universidad De San Martin De Porres");
      documento.open();
      
      titulo.setAlignment(1);
      documento.add(titulo);
      documento.add(header);
    
      documento.add(parrafo);
      
       
      
        PdfPTable tabla = new PdfPTable(7);
             
            tabla.addCell("Establecimiento");
            tabla.addCell("Tipo");
            tabla.addCell("Unidad");
            tabla.addCell("Dotacion");
            tabla.addCell("Consumo");
            tabla.addCell("Cantidad");
            tabla.addCell("Observaciones");
            
            
         for(TablaDotacion TC: this.tabladotacion){
                tabla.addCell(TC.getEsta()); 
                tabla.addCell(TC.getTipo());
                tabla.addCell(TC.getSelector3());
                tabla.addCell(TC.getDotacion());
                tabla.addCell(TC.getConsumo());
                tabla.addCell(TC.getCantidad());
                tabla.addCell(TC.getObser());

                
            }
         documento.add(tabla);
         documento.close();

         
    JOptionPane.showMessageDialog(null, "Reporte creado correctamente.");
      }catch(DocumentException | IOException e){
      System.err.println("Error en PDF o ruta de imagen" + e);
      JOptionPane.showMessageDialog(null, "Error al generar PDF");
      
      } 
  
      /*  try {
      TablaDotacion.print(); // Imprime el jTable
      } catch (PrinterException ex) {
      } */

    }//GEN-LAST:event_BTNExportActionPerformed
   
    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        TextSelector3.setText("");
        Text_Cantidad1.setText("");
        jTextField1.setText("");
        Select_Establecimiento.removeAllItems();
        
    }//GEN-LAST:event_LimpiarActionPerformed

    private void BTNExport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNExport1ActionPerformed
          try{
            ExportoExcelDotacion OBj = new ExportoExcelDotacion();
            OBj.exportarExcel(TablaDotacion);
        }catch(IOException ex){
            Logger.getLogger(VariacionConsumo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BTNExport1ActionPerformed

    private void Select_EstablecimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Select_EstablecimientoMouseClicked
        OpcionesSelector OPS= new OpcionesSelector();
        
        int posicion=Selec_Dotaciones.getSelectedIndex();
        String [] vector=OPS.OpcionesSelector(posicion);
       
        Select_Establecimiento.removeAllItems();
        for (String vecto:vector){
            Select_Establecimiento.addItem(vecto);
        }
        
        
        
    // String seleccionado=(String)Select_Establecimiento.getSelectedItem();
    }//GEN-LAST:event_Select_EstablecimientoMouseClicked

    @SuppressWarnings("empty-statement")
    private void Selec_DotacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Selec_DotacionesMouseClicked
  
       
    }//GEN-LAST:event_Selec_DotacionesMouseClicked

    private void Select_EstablecimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Select_EstablecimientoActionPerformed
   Selector3.removeAllItems();          
      
  
    }//GEN-LAST:event_Select_EstablecimientoActionPerformed

    private void Select_EstablecimientoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Select_EstablecimientoItemStateChanged
       /* if(evt.getStateChange()==ItemEvent.SELETED){
        }
*/
        
    }//GEN-LAST:event_Select_EstablecimientoItemStateChanged

    private void TextSelector3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextSelector3KeyTyped
         char validar = evt.getKeyChar();
                 
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null,"Solo se aceptan numeros");
        }
    }//GEN-LAST:event_TextSelector3KeyTyped

    private void Text_Cantidad1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Text_Cantidad1KeyTyped
         char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null,"Solo se aceptan numeros");
        }
    }//GEN-LAST:event_Text_Cantidad1KeyTyped

    private void TablaDotacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDotacionMousePressed
      DefaultTableModel modelo = (DefaultTableModel) TablaDotacion.getModel();
       
        int val = modelo.getRowCount(); 
        if(val>0){
            modelo.removeRow(val-1);
        }      
        
    }//GEN-LAST:event_TablaDotacionMousePressed

    private void Selector3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Selector3ActionPerformed
      
        
       
    }//GEN-LAST:event_Selector3ActionPerformed

    private void Selector3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Selector3MouseClicked
        OpcionesSelector OPS= new OpcionesSelector();
        int pos1=Selec_Dotaciones.getSelectedIndex();
        int pos2=Select_Establecimiento.getSelectedIndex();
        String [] vector=OPS.OpcionesSelector3(pos1,pos2);
       
        Selector3.removeAllItems();
        for (String vecto:vector){
            Selector3.addItem(vecto);
        }
    }//GEN-LAST:event_Selector3MouseClicked

    private void TablaDotacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDotacionMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaDotacionMouseEntered

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNExport;
    private javax.swing.JButton BTNExport1;
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JButton Limpiar;
    public javax.swing.JComboBox<String> Selec_Dotaciones;
    public javax.swing.JComboBox<String> Select_Establecimiento;
    private javax.swing.JComboBox<String> Selector3;
    private javax.swing.JTable TablaDotacion;
    private javax.swing.JTextField TextSelector3;
    private javax.swing.JTextField Text_Cantidad1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables


}
