/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Abastecimiento;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Component;
import java.awt.print.PrinterException;
import java.io.FileOutputStream;
import java.io.IOException;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cristian
 */
public class VariacionConsumo extends javax.swing.JPanel {

    /**
     * Creates new form VariacionConsumo
     */
    Paragraph titulo;
     List<TablaConsumo>  tablaconsumo;
     
    public VariacionConsumo() {
        initComponents();
        tablaconsumo = new ArrayList<>();
    }
    DefaultTableModel model = new DefaultTableModel();
    variacion_consumo data = new variacion_consumo(model);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        txt_k1 = new javax.swing.JComboBox<>();
        txt_k2 = new javax.swing.JComboBox<>();
        txt_poblacion = new javax.swing.JTextField();
        txt_ano = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        mytable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BtnGuardar = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setMaximumSize(new java.awt.Dimension(3757, 3757));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(1, 1));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(50, 100));

        jPanel2.setBackground(new java.awt.Color(242, 242, 242));
        jPanel2.setPreferredSize(new java.awt.Dimension(720, 1000));

        txt_k1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un rango", "Poblaciones mayores", "Poblaciones menores",
            "Clima uniforme","Clima variables","Poblaciones pequeñas" }));

txt_k2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un rango", "2.000 a 10.000 hab","10.000 hab < P", "P < 5.000", "5.000< P < 20.000",
    "20.000 < P", "Aldeas", "Pueblos", "Ciudades", "Urbano" , "Rural"}));

    txt_poblacion.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            txt_poblacionKeyTyped(evt);
        }
    });

    txt_ano.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            txt_anoActionPerformed(evt);
        }
    });
    txt_ano.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            txt_anoKeyTyped(evt);
        }
    });

    mytable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
        new String [] {
            "Codigo", "Año", "Población", "Consumo(L/hab.d)","Qm (L/s)",
            "Factor mayoración","Qmd (L/s)", "Qmh (L/s)","Qmm(L/s)"
        }
    ));
    mytable.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mousePressed(java.awt.event.MouseEvent evt) {
            mytableMousePressed(evt);
        }
    });
    jScrollPane2.setViewportView(mytable);

    jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pdf.png"))); // NOI18N
    jButton2.setText("PDF");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });

    jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/excel.png"))); // NOI18N
    jButton3.setText("EXCEL");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
    jLabel1.setText("VARIACIÓN DE CONSUMO");

    jLabel2.setText("Ingrese año:");

    jLabel3.setText("Ingrese población:");

    jLabel4.setText("K1:");

    jLabel5.setText("K2:");

    BtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
    BtnGuardar.setText("Generar");
    BtnGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnGuardarActionPerformed(evt);
        }
    });

    BtnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Actions-edit-delete-icon.png"))); // NOI18N
    BtnLimpiar.setText("Limpiar");
    BtnLimpiar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnLimpiarActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(145, 145, 145)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_k1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_ano, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(BtnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(64, 64, 64)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(txt_poblacion, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                .addComponent(txt_k2, 0, 208, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addComponent(BtnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel1)))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(104, 104, 104)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(104, 104, 104)
                    .addComponent(jButton2)
                    .addGap(18, 18, 18)
                    .addComponent(jButton3)))
            .addContainerGap(94, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(48, 48, 48)
            .addComponent(jLabel1)
            .addGap(46, 46, 46)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(jLabel3))
            .addGap(18, 18, 18)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txt_poblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txt_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(jLabel5))
            .addGap(13, 13, 13)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txt_k1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txt_k2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(26, 26, 26)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(BtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(29, 29, 29)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
            .addGap(42, 42, 42)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton2)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(317, 317, 317))
    );

    jScrollPane1.setViewportView(jPanel2);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_anoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_anoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_anoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
/*          try {
            mytable.print(); // Imprime el jTable
        } catch (PrinterException ex) { }
        */

    try {

      Document documento = new Document();

      String ruta = System.getProperty("user.home");
      PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/OneDrive/Escritorio/" + "CalculosConsumo" + ".pdf"));
      com.itextpdf.text.Image header = com.itextpdf.text.Image.getInstance("src/imagenes/USMP-2020.png");
      header.scaleToFit(200, 400);
      header.setAlignment(Chunk.ALIGN_CENTER);
      Paragraph parrafo = new Paragraph();
      parrafo.setAlignment(Paragraph.ALIGN_CENTER);
      parrafo.add("Tabla.2 Resultado de Calculos de variacion de consumo \n \n");
      parrafo.setFont(FontFactory.getFont("Tahoma", 18, Font.BOLD, BaseColor.DARK_GRAY));
      titulo= new Paragraph("Universidad De San Martin De Porres");
      documento.open();
       titulo.setAlignment(1);
      documento.add(titulo);
      
      documento.add(header);
      documento.add(parrafo);
      
       
      
        PdfPTable tabla = new PdfPTable(9);
        
            tabla.addCell("Codigo");
            tabla.addCell("Año");
            tabla.addCell("Poblacion");
            tabla.addCell("Consumo(L/hab.d)");
            tabla.addCell("Qm (L/s)");
            tabla.addCell("Factor mayoración");
            tabla.addCell("Qmd (L/s)");
            tabla.addCell("Qmh (L/s)");
            tabla.addCell("Qmm (L/s)");

            
         for(TablaConsumo TC: this.tablaconsumo){
                tabla.addCell(TC.getCodigo()); 
                tabla.addCell(TC.getAno());
                tabla.addCell(TC.getPoblacion());
                tabla.addCell(TC.getConsumo());
                tabla.addCell(TC.getQm());
                tabla.addCell(TC.getFactormayoracion());
                tabla.addCell(TC.getQmd());
                tabla.addCell(TC.getQmh());
                tabla.addCell(TC.getQmm());
            }
         documento.add(tabla);
         documento.close();

         
    JOptionPane.showMessageDialog(null, "Reporte creado correctamente.");
      }catch(DocumentException | IOException e){
      System.err.println("Error en PDF o ruta de imagen" + e);
      JOptionPane.showMessageDialog(null, "Error al generar PDF");
      
      } 

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try{
            clsExportarExcel obj = new clsExportarExcel();
            obj.exportarExcel(mytable);
        }catch(IOException ex){
            Logger.getLogger(VariacionConsumo.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
            //-------Decalracion de variables-------//
         if (txt_ano.getText().isEmpty() || txt_poblacion.getText().isEmpty()){
             getToolkit().beep();
             JOptionPane.showMessageDialog(null,"Por favor, llenar los campos");
         }else {
             int ano = 0; 
            double poblacion = 0.0;
            String k1 = "",k2 = "";
            double consumo,Qm,Qmd, factormayoracion = 1.50, Qmh,Qmm;

            ano = Integer.valueOf(txt_ano.getText());
            poblacion = Double.valueOf(txt_poblacion.getText());
            k1 =  txt_k1.getSelectedItem().toString();
            k2 = txt_k2.getSelectedItem().toString();

            data.generate_information(ano, poblacion, k1, k2);

            consumo = data.getConsumo();
            Qm = data.getQm();
            Qmd = data.getQmd();
            Qmh = data.getQmh();
            Qmm = data.getQmm();
            int codigo = data.getContador();
            
            TablaConsumo TC1 = new TablaConsumo();
            
               TC1.setCodigo(String.valueOf(codigo));
               TC1.setAno(String.valueOf(ano));
               TC1.setPoblacion(String.valueOf(poblacion));
               TC1.setConsumo(String.valueOf(consumo));
               TC1.setQm(String.valueOf(Qm));
               TC1.setFactormayoracion(String.valueOf(factormayoracion));
               TC1.setQmd(String.valueOf(Qmd));
               TC1.setQmh(String.valueOf(Qmh));
               TC1.setQmm(String.valueOf(Qmm));
     
              tablaconsumo.add(TC1);
            
            model = (DefaultTableModel) data.datos_Tabla(model,codigo,ano,poblacion,consumo,Qm,Qmd,Qmh,Qmm, factormayoracion);
            mytable.setModel(model);
             
            txt_k2.setSelectedItem(ano);
         }
         

    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
       txt_ano.setText("");
       txt_poblacion.setText("");
       txt_k1.setSelectedItem("Seleccione un rango");
       txt_k2.setSelectedItem("Seleccione un rango");
       
       
 
     
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    private void txt_anoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_anoKeyTyped
        // TODO add your handling code here:
        
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null,"Solo se aceptan numeros");
        }
    }//GEN-LAST:event_txt_anoKeyTyped

    private void txt_poblacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_poblacionKeyTyped
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null,"Solo se aceptan numeros");
        }
    }//GEN-LAST:event_txt_poblacionKeyTyped

    private void mytableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mytableMousePressed
       DefaultTableModel modelo = (DefaultTableModel) mytable.getModel();
        
        int val = modelo.getRowCount(); 
        if(val>0){
            modelo.removeRow(val-1); 
        }
    }//GEN-LAST:event_mytableMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable mytable;
    private javax.swing.JTextField txt_ano;
    private javax.swing.JComboBox<String> txt_k1;
    private javax.swing.JComboBox<String> txt_k2;
    private javax.swing.JTextField txt_poblacion;
    // End of variables declaration//GEN-END:variables
}
